apiVersion: batch/v1
kind: Job
metadata:
  name: spark-demo
spec:
  template:
    spec:
      containers:
      - name: spark
        image: bitnami/spark:latest
        command: ["spark-submit", "--version"]
      restartPolicy: Never
